### ISSUE TITLE
Tables coming as a stack

### ISSUE THREAD

**Issue by nabiltkarim** [natancabral/pdfkit-table#10]
Hello, thank you for this amazing library. I'm trying to place 4 tables side by side on the same `y` panel but they keep on appearing one after another. Gave the same `y` value for all 4 but still coming on top of each other.
<img width="280" alt="Screenshot 2021-11-17 at 1 43 20 AM" src="https://user-images.githubusercontent.com/20380210/142037704-5be70c71-b5a8-49c4-87dd-ed235f1caab2.png">
r

**Comment by natancabral** [comment]
Hi, @nabiltkarim. Thanks to come here. 
You found a bug! :)

Upgrade version:
`$ npm install pdfkit-table@latest`

Check this:
https://github.com/natancabral/pdfkit-table#0170

**Comment by natancabral** [comment]
[document-4.pdf](https://github.com/natancabral/pdfkit-table/files/7549955/document-4.pdf)

**Comment by natancabral** [comment]
**Sample**
[document.pdf](https://github.com/natancabral/pdfkit-table/files/7549993/document-4.pdf)

**Comment by nabiltkarim** [comment]
Legend! Thank you so much
