### ISSUE TITLE
Change the height of the header and the rows

### ISSUE THREAD

**Issue by Kayaba-Attribution** [natancabral/pdfkit-table#11]
Change the height of the header and the rows

Is there any way to do this?

It could be something similar to width but I couldn't find anything on the docs

**Comment by natancabral** [comment]
Hi, @Kayaba-Attribution 
Like height fixed or padding space?

```
let options = {
   columnSpacing: 15, // padding height
}
```
Works for you?

**Comment by Kayaba-Attribution** [comment]
@natancabral Yes! that worked thank you a lot
