### ISSUE TITLE
Add images inside the table?

### ISSUE THREAD

**Issue by Kayaba-Attribution** [natancabral/pdfkit-table#12]
Is there a way to add an image inside the table?

When I try to add it, it is rendered at the top left of the table and the string ```[object PDFDocument]``` is on the cell

**Comment by Kayaba-Attribution** [comment]
Sorry, didnt know about the renderer option.

here is the solution for anyone that is searching:

```
const createLink2 = (value, indexColumn, indexRow, row, rectRow, rectCell) => {
    const { x, y, width, height } = rectCell;
    doc.image('a.png',x, y, { width: 8 });
    return `   ${value}`;
}
```

**Comment by natancabral** [comment]
Nice idea!

```
  const base64 = "data:image/png;base64,...";
  const imageRenderer = (value, indexColumn, indexRow, row, rectRow, rectCell) => {
    const { x, y, width, height } = rectCell;
    doc.image(base64, x, y, { height: height});
    return ''; // void return
  }
```
or
```
    doc.image(base64, x, y, { fit: [width, height], align: 'center', valign: 'center'});

```

**Comment by hakimscode** [comment]
How to adjust the height of the row with image?

I can't use minRowHeight because my table just have 1 row that have image

**Comment by Adamk1017** [comment]
These solutions dont seem to work for me, is it possible to show how you would add it to the table header please?
