### ISSUE TITLE
Align text inside cells

### ISSUE THREAD

**Issue by Daalb** [natancabral/pdfkit-table#13]
Is there a way to align text (left, right, center) within a cell?.

The documentation does not explain whether it is possible to :(

**Comment by natancabral** [comment]
Hi, @Daalb 
Chech this: https://github.com/natancabral/pdfkit-table#headers
Example
```
headers: [
  {label:"Name", property:"name", valign: "center", headerAlign:"right", },
]
```

**Comment by Daalb** [comment]
Oh, thank you. Sorry about that. I got confused because I saw the property in the header section 😅😅

**Comment by natancabral** [comment]
hehe no problem, @Daalb. Good luck.

**Comment by oscarboc** [comment]
with headerAlign Not align in rows text
