### ISSUE TITLE
Able to remove the line from a table row

### ISSUE THREAD

**Issue by lucswart** [natancabral/pdfkit-table#14]
Is there already the functionality to remove the horizontal lines from the table? Would be very nice to have that!

**Comment by natancabral** [comment]
Hi, @lucswart. Thanks to come here.
Nice idea!

Upgrade version:
$ npm install pdfkit-table@latest

Check this:
https://github.com/natancabral/pdfkit-table#0172

**Comment by lucswart** [comment]
Wow, that was fast! Thanks a lot, will check it out soon.
