### ISSUE TITLE
Rotating text

### ISSUE THREAD

**Issue by phorcys420** [natancabral/pdfkit-table#15]
![image](https://user-images.githubusercontent.com/57866459/147923950-e7428539-c300-4d90-88f7-dece7190f315.png)

I wanna achieve something like this, is that possible using pdfkit-table ?

**Comment by natancabral** [comment]
Hi, @phorcys420,
Rotate only header data?

**Comment by phorcys420** [comment]
whoops, had my issue notifications off, sorry..
I want the up section to look exactly like that, I don't know what you mean by "header data" ?

**Comment by natancabral** [comment]
No problem. 
You need only a vertical header?

**Comment by cpdk** [comment]
Also looking for this functionality - as shown in screenshot above

**Comment by mintheinwin** [comment]
@phorcys420 Hi Phorcy, Already have fixed this issues? I also want to rotate table view like this issues , how you call method for rotation table and text ?

**Comment by mintheinwin** [comment]
> Hi, @phorcys420,
> Rotate only header data?

@natancabral Hi Sir, How to call method for rotate table view ?
