### ISSUE TITLE
Vertical text overlap on row

### ISSUE THREAD

**Issue by Kayaba-Attribution** [natancabral/pdfkit-table#17]
Hi again!

Is there a way to fix this?

I would like to increase the row width, is that possible?

![image](https://user-images.githubusercontent.com/63566185/149260706-0c49bcab-b72d-4673-a9db-caddbcab0c3a.png)

This is my table code:

```javascript
doc.table(OnlyOwnerTable, {
    columnSpacing: 10,
    width: 490,
    columnsSize: [200, 220, 90],
    padding: 20,
    align: "center",
    prepareHeader: () => doc.font("fonts/Roboto-Regular.ttf").fontSize(11), // {Function}
    prepareRow: (row, indexColumn, indexRow, rectRow) => doc.font("fonts/Roboto-Regular.ttf").fontSize(10).fillColor('#292929'), // {Function}
});
```

any help is very appreciated

**Comment by natancabral** [comment]
Hi, @Kayaba-Attribution 
Show me the table code. $OnlyOwnerTable value.

**Comment by natancabral** [comment]
`
  const table01 = {
   "headers" : ["A", "B", "C"],
    "rows": [
        [ "Name 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id est ipsum. Fusce scelerisque maximus justo, lacinia ornare felis iaculis nec.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id est ipsum. " ],
        [ "Name 2", "Age 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id est ipsum. Fusce." ],
        [ "Name 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id est ipsum.", "Year 3" ],
        [ "Name 4", "Age 4", "Year 4" ],
    ],
  };

  await doc.table(table01, {
    columnSpacing: 10,
    width: 350,
    padding: 20,
    columnsSize: [200, 220, 135],
    align: "center",
    prepareHeader: () => doc.fontSize(11), // {Function}
    prepareRow: (row, indexColumn, indexRow, rectRow) => doc.fontSize(10).fillColor('#292929'), // {Function}
  });

  doc.end();
`

**Comment by Kayaba-Attribution** [comment]
Thank you the error was that my table contained nested arrays, I got rid of them and it worked !

Thank you!
