### ISSUE TITLE
PDF is empty after the first time

### ISSUE THREAD

**Issue by Acment** [natancabral/pdfkit-table#2]
Hello again, the links in row works perfectly, thank you so much for that. Now I just have found an issue. 
When I run the local server for the first time and then I generate a pdf it works ok, but when I generate the second one, the pdf is empty.

PDF ok:
![pdf full](https://user-images.githubusercontent.com/65464740/128771331-5b5189a0-c77c-466f-a679-d20f659e379f.png)

Second PDF empty:
![image](https://user-images.githubusercontent.com/65464740/128771701-2f181bba-3b46-479f-9a77-57256334ec9e.png)

**Comment by natancabral** [comment]
Hi, Eduardo Miranda. 
I believe that you need initialize **new PDFDocument** again every time you create a pdf file.

```js
var doc; 
function createPDF () {
  doc = new PDFDocument({ margin: 30 });
  // your code
  doc.end();
}
```

If not work, show me your code.

**Comment by Acment** [comment]
That worked perfectly! You are amazing man, thank you a lot again😭💕
