### ISSUE TITLE
Problem with row height when using barcode font in cell

### ISSUE THREAD

**Issue by LouiseEH** [natancabral/pdfkit-table#25]
Hi,

I change font for setting a barcode in a cell in a table, and change the font back again afterwards.
When I do this, the row height is not adjusted to fit the barcode string though.
The only workaround I can find, is adding newlines in one of the other cells, and adding the barcodes after the table has been generated, by saving the x and y coordinates for the cell location where the barcodes should be added.

**Comment by natancabral** [comment]
Hi @LouiseEH,
Please, show me the code.

**Comment by LouiseEH** [comment]
When using doc.image I have the same issue - the row height is not adjusted to fit the image:

`const table = {
    title: '',
    headers: [
      { property: 'page', label: 'Page', align: 'center', headerOpacity: OPACITY },
      { property: 'sku', label: 'Item no', headerOpacity: OPACITY },
      {
        property: 'barcode', label: 'Item Barcode', headerOpacity: OPACITY, renderer: (value, indexColumn, indexRow, row, rectRow, rectCell) => {
          const { x, y, width, height } = rectCell
          if (row.barCodePng) {
            doc.image(row.barCodePng, x, y + 5, { fit: [60, 22], align: 'center', valign: 'center' })
          }
          return ''
        }
      },
      { property: 'itemDescription', label: 'Item Description', headerOpacity: OPACITY },
      { property: 'packageQuantity', align: 'center', label: 'Packed Per', headerOpacity: OPACITY },
      { property: 'costPrice', align: 'right', label: 'Cost Price', headerOpacity: OPACITY },
      { property: 'retailPrice', align: 'right', label: 'Rec. Retail Price', headerOpacity: OPACITY }
    ],
    datas: datas,
    rows: [
    ],
  }`

I had to anonymize data a bit on the attached image, but you can see the barcode image overlaps the row line.

![image](https://user-images.githubusercontent.com/50172122/167031187-f06abfd3-03cc-4200-a67f-f9c35a6dae5a.png)

**Comment by natancabral** [comment]
Try last version, 0.1.90
```
$ npm install pdfkit-table@latest
```
Use minRowHeight on options
```js
  options: {
    minRowHeight: 30
  }
```
See:
https://github.com/natancabral/pdfkit-table#0190

**Comment by natancabral** [comment]
You can change fontFamily that way:
https://github.com/natancabral/pdfkit-table#0188
```js
let localType = "./font/Montserrat-Regular.ttf";
const table = {
  title: { label: 'Title Object 2', fontSize: 30, color: 'blue', fontFamily: localType },
}
```

**Comment by natancabral** [comment]
Another alternative to calc image by image, inside renderer:
```js
      renderer: (value, indexColumn, indexRow, row, rectRow, rectCell) => { 
        doc.positionY += 50; // image height
        // your code or image 
      }
```

**Comment by LouiseEH** [comment]
Hi @natancabral,
That works - thank you for the fast and helpful reply

**Comment by natancabral** [comment]
Hi, @LouiseEH 
If we done, close, please. 
Thanks!
