### ISSUE TITLE
Vertical dividers

### ISSUE THREAD

**Issue by rafaelfquadros** [natancabral/pdfkit-table#26]
Is there an option for vertical dividers?

**Comment by natancabral** [comment]
Hi, @rafaelfquadros 
Respondi essa pergunta aqui:
https://github.com/natancabral/pdfkit-table/issues/16#event-5891200400

Nativamente não desenvolvi ainda pois não verifiquei a performance.
Boa sorte!

**Comment by rafaelfquadros** [comment]
Valeu Natan !
