### ISSUE TITLE
Problem Rows

### ISSUE THREAD

**Issue by JoseLuis21** [natancabral/pdfkit-table#28]
prepareRow with doc.moveUp(50) not working for first row 

![image](https://user-images.githubusercontent.com/7219692/161847167-f897767e-274b-461c-80a1-ce8929f3072a.png)

![image](https://user-images.githubusercontent.com/7219692/161847199-1e21631e-4f7e-48e4-bcb0-5d8239eb3feb.png)

**Comment by natancabral** [comment]
Hi, @JoseLuis21,  
Let me see your code... and my.

**Comment by natancabral** [comment]
Try last version, 0.1.90
```
$ npm install pdfkit-table@latest
```
See:
https://github.com/natancabral/pdfkit-table#0188

**Comment by natancabral** [comment]
Try a new package typescript (async)
```
$ npm i pdfkit-table-ts@latest
```
Sample init code
https://github.com/natancabral/pdfkit-table-ts

PDF Sample:
[example-2.pdf](https://github.com/natancabral/pdfkit-table/files/8757735/example-2.pdf)

**Comment by JoseLuis21** [comment]
Thanks @natancabral
