### ISSUE TITLE
not working with node 8

### ISSUE THREAD

**Issue by mehmetunubol** [natancabral/pdfkit-table#3]
https://github.com/natancabral/pdfkit-table/blob/b4548dc766d3f0a40cf15e68380a36daeaa12a87/index.js#L19

**Comment by mehmetunubol** [comment]
> https://github.com/natancabral/pdfkit-table/blob/b4548dc766d3f0a40cf15e68380a36daeaa12a87/index.js#L19

Changing this line to below resolves the problem:
`  addBackground ({x, y, width, height}, fillColor, fillOpacity) {`

**Comment by natancabral** [comment]
Done! Thanks, @mehmetunubol.
