### ISSUE TITLE
Background color per column

### ISSUE THREAD

**Issue by gokugen** [natancabral/pdfkit-table#30]
Hi,
I would like to know if there is a way to add a background color per column and not per line?

Thank you very much

**Comment by natancabral** [comment]
Hi, @gokugen,
Add on header **columnColor** and **columnOpacity** properties.

**Params**
https://github.com/natancabral/pdfkit-table#headers

**Sample**
```
const tableArray = {
  title: 'My Title',
  headers: [
    { "label":"Name", "property":"name", "width":100, "columnColor": "#eeeeee", columnOpacity: 0.9},
    { "label":"Age", "property":"age", "width":100 },
  ],
  datas: [
    { name: "Name 1", age: "Age 1" },
  ]
};
```
