### ISSUE TITLE
Cannot stylize title

### ISSUE THREAD

**Issue by RastaGrzywa** [natancabral/pdfkit-table#31]
I've got a bit of a trouble to style title of table. I wonder if there's any possibility to do this.
Based on simple example:

    

    let doc = new PDFDocument({ margin: 30, size: 'A5' });
    doc.pipe(fs.createWriteStream("./document.pdf"));
    doc.font("./app/fonts/Montserrat-Regular.ttf").fontSize(25);
    
    const table = {
      title: "Title",
      subtitle: "Subtitle",
      headers: ["Country", "Conversion rate", "Trend"],
      rows: [
        ["Switzerland", "12%", "+1.12%"],
        ["France", "67%", "-0.98%"],
        ["England", "33%", "+4.44%"],
      ],
    };
    doc.font("./app/fonts/Montserrat-Regular.ttf").fontSize(25).table( table, { 
      width: 300,
    }); 

    doc.end();

I don't know why it doesn't work or how it should work. (Note: I've successfully formatted headers and rows with provided font/size)

**Comment by natancabral** [comment]
Try last version, 0.1.88
```
$ npm install pdfkit-table@latest
```
See:
https://github.com/natancabral/pdfkit-table#0188

Document:
[document-13.pdf](https://github.com/natancabral/pdfkit-table/files/8620878/document-13.pdf)

```js
const fs = require("fs");
// const PDFDocument = require("pdfkit-table");

;(async function(){

let doc = new PDFDocument({ margin: 30, size: 'A5' });
doc.pipe(fs.createWriteStream("./document.pdf"));

// table
const table = {
  title: "Title",
  subtitle: "Subtitle",
  headers: ["Country", "Conversion rate", "Trend"],
  rows: [
    ["Switzerland", "12%", "+1.12%"],
    ["France", "67%", "-0.98%"],
    ["England", "33%", "+4.44%"],
  ],
};

// set font file
let localType = "./font/Montserrat-Regular.ttf";

// see options
doc.table( table, { 
  width: 300,
  prepareHeader: () => doc.font(localType).fontSize(8),
  prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {
    doc.font(localType).fontSize(8);
  },
}); 

doc.moveDown();

// table 2
const table2 = {
  title: { label: 'Title Object 2', fontSize: 30, color: 'blue', fontFamily: localType },
  subtitle: "Subtitle 2",
  headers: ["Country 2", "Conversion rate 2", "Trend 2"],
  rows: [
    ["Switzerland", "12%", "+1.12%"],
    ["France", "67%", "-0.98%"],
    ["England", "33%", "+4.44%"],
  ],
};

// see options 2
doc.table( table2, { 
  width: 350,
  prepareHeader: () => doc.font(localType).fontSize(8),
  prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {
    doc.font(localType).fontSize(8);
  },
}); 

doc.end();
})();
```

**Comment by natancabral** [comment]
![Screenshot from 2022-05-04 10-55-49](https://user-images.githubusercontent.com/3301214/166696558-5321c185-857b-4586-9ccf-a3f80fe1e4b3.png)

**Comment by natancabral** [comment]
@RastaGrzywa, works for you?
