### ISSUE TITLE
Getting typescript compilation error

### ISSUE THREAD

**Issue by saachinsiva** [natancabral/pdfkit-table#35]
Hello

When I use any version after 0.8.6, I am getting below error. Please advise.

> node_modules/pdfkit-table/index.ts:1:1 - error TS1208: 'index.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

**Comment by natancabral** [comment]
Try last version, 0.1.94
```shell
$ npm install pdfkit-table@latest

```
