### ISSUE TITLE
headers on new page?

### ISSUE THREAD

**Issue by QAnders** [natancabral/pdfkit-table#4]
Wow, I really love this. awesomely done!
I was racking my brain on how to be able to create an invoice with a decent table and then stumbled upon this while Googling...

However, I would need the headers of the table on each new page...

I've been fiddling around in `this.on('pageAdded', () => {}` but I can't seem to get it right as the "styling" (font and color) on the previous page table is then lost...
What I've got now (which feels a bit "clunky" is:
```
this.on('pageAdded', () => {
      startY = this.page.margins.top;
      rowBottomY = 0;
      // +++ AW TEST
     // Add table header on each page
      table.headers.forEach((header, i) => {
        this.text(header, startX + i * columnContainerWidth, startY, {
          width: columnWidth,
          align: 'left'
        });
      });
      const rowHeight = computeRowHeight(table.headers);
      rowBottomY = Math.max(startY + rowHeight, rowBottomY);
      this.moveTo(startX, rowBottomY - rowSpacing * 0.5)
        .lineTo(startX + usableWidth, rowBottomY - rowSpacing * 0.5)
        .lineWidth(2)
        .stroke();
      startY = rowBottomY + rowSpacing;
      // --- AW TEST
    });
```

Any suggestions?

**Comment by natancabral** [comment]
Woow, nice code! Thanks for write, I really appreciate it.
I rewrote the code adding header on all pages. 
Try install 0.1.47 version 

`$ npm install pdfkit-table@latest`

I hope its helps

**Comment by QAnders** [comment]
Thanks so much!

I'll check it out tomorrow and let you know!

**Comment by natancabral** [comment]
Keeps styling (font and color) on the previous page table with **prepareHeader()** :+1: 
```
const table = {
  //...
}
doc.table( table, {
  prepareHeader: () => doc.font("Helvetica-Bold").fontSize(15)
});

```

**Comment by QAnders** [comment]
Wow! Much nicer look as well!

I do get something weird happening on pages after the second page when there are many pages... 
It's really weird... PDF's with up to 19 pages looks totally fine but as soon as they have more than 20 pages one page, only one page, has a messed up header... I've compared the data and it is no difference really that I can see for the items that "break" the header.

Sometimes it's page 3, other times page 4 or 5 but it only happens on one page, all the other pages look fine.

![image](https://user-images.githubusercontent.com/12028885/133555727-9c79a84f-42ab-4f77-adfa-4439c6342cf5.png)

![image](https://user-images.githubusercontent.com/12028885/133556139-baec9fcd-a77b-434a-a979-185f6c371df7.png)

**Comment by QAnders** [comment]
Me again... sorry...

I adjusted the maxY a bit by lowering it by 5 points: `const maxY = this.page.height - (this.page.margins.bottom + 5);`

Like that it works for all the previous samples I tested before. Also the line that spilled over into the footer is then OK.

**Comment by natancabral** [comment]
Hi, @QAnders. So many questions.
I changed code to: `const maxY = this.page.height - (this.page.margins.top + this.page.margins.bottom);`
I adjusted  Separate function used on header too.
Try again.
`$ npm install pdfkit-table@latest`
[file-table-local-large3.pdf](https://github.com/natancabral/pdfkit-table/files/7185598/file-table-local-large3.pdf)

**Comment by QAnders** [comment]
Nice, thanks! I'll check it out!

Much appreciated!
