### ISSUE TITLE
Multiple style in datas (or headers)

### ISSUE THREAD

**Issue by ElBuenAnvita** [natancabral/pdfkit-table#42]
Hi! I just wanted to know if it's possible to set different two different style to text in a cell.

During my search I found that you can do something like [this](https://github.com/natancabral/pdfkit-table#options-row):
```
{ name: 'bold:Jack' }
```

And it actually came bold.
But I wasn't able to do something like this:
> **Jack** Sparrow

My suggestion is to allow to set a String, an Object OR an Array in the property (in this case `name`) on datas and the result would be a concatenation of the strings styled. For example:
```
{ name: [
  { text: 'bold:Jack ' },
  { text: 'Sparrow ' },
  { text: 'THE CAPTAIN', options: { fontFamily: 'Times-Italic' } } 
] }
```
And return something like
> **Jack** Sparrow _THE CAPTAIN_

This is my solution, but if there is any better way to implement it I let it in your own; or please tell me if this feature is already possible with the function `prepareRow` or by other means. Thanks.

**Comment by natancabral** [comment]
Hi, @ElBuenAnvita.
Nice question. Use renderer to manipulate cells, example:

```
const fs = require("fs");
const PDFDocument = require("pdfkit-table");

;(async function(){

  let doc = new PDFDocument({ margin: 30, });
  doc.pipe(fs.createWriteStream(`./example-17.pdf`));

  function concatFunction(value, indexColumn, indexRow, row, rectRow, rectCell)
  {
    // READ DOCUMENTATION:
    // https://pdfkit.org/docs/text.html
    const {x, y, width, height} = rectCell;
    const padding = 5;
    doc
    .font('Courier-Bold')
    .fillColor('red')
    .text(`${row.first_name} `, x, y + padding,  {
      width: width,
      continued: true
    })
    .font('Courier')
    .fillColor('blue')
    .text(`${row.middle_name} `,  {
      width: width,
      continued: true
    })
    .fillColor('green')
    .text(`${row.last_name} `,  {
      width: width,
      continued: true
    })
    return ``; 
  }

  const table = {
    headers: [
      { label:"Name", property: 'name', renderer: concatFunction },
    ],
    datas: [
      { first_name: 'Jack', middle_name: 'Sparrow', last_name: 'THE CAPTAIN', },
    ]
  };
  
  await doc.table(table, {
    title: 'Cast Movies',
  });
  
  doc.end();
    
})();

```

**Comment by natancabral** [comment]
### PDF Example here
[example-17.pdf](https://github.com/natancabral/pdfkit-table/files/8879230/example-17.pdf)

**Comment by natancabral** [comment]
That's way lost performance, high coast to server/machine:
```
{ name: [
  { text: 'bold:Jack ' },
  { text: 'Sparrow ' },
  { text: 'THE CAPTAIN', options: { fontFamily: 'Times-Italic' } } 
] }
```

**Comment by natancabral** [comment]
![Screenshot from 2022-06-10 15-46-01](https://user-images.githubusercontent.com/3301214/173130819-50fded7e-2f6f-409a-a057-70f8185d3ae7.png)

**Comment by natancabral** [comment]
Hi, @ElBuenAnvita 
If we done, close, please.
Thanks!

**Comment by ElBuenAnvita** [comment]
Thanks for the very quick response @natancabral! Worked flawlessly :D

Just another little thing before closing, how can I add a line with this same renderer function so it gets like this
> Jack Sparrow
> THE CAPTAIN

in the same cell? Tried with `\n` and `continue: false` in the same code but both seems like it doesn't fit in the height of the cell (?).

```js
doc
    .font('Courier-Bold')
    .fillColor('red')
    .text(`${row.first_name} `, x, y + padding,  {
      width: width,
      continued: true
    })
    .font('Courier')
    .fillColor('blue')
    .text(`${row.middle_name} `,  {
      width: width,
      continued: false // <-- Here
    })
    .fillColor('green')
    .text(`${row.last_name}`,  {
      width: width,
      continued: true
    })
```
![image](https://user-images.githubusercontent.com/37051987/173414471-2ef35846-dec3-4e7c-ae07-212b1cce241b.png)

Again thanks and sorry for the inconvenience!

**Comment by natancabral** [comment]
Use `minRowHeight` on options OR calc row height, but you need read pdfkit documentation.

- minRowHeight
https://github.com/natancabral/pdfkit-table#options

- calc row height nativaly 
Use `doc.heightOfString(text, options) `
https://pdfkit.org/docs/text.html

**Comment by ElBuenAnvita** [comment]
Thanks! Since `minRowHeight` is applied to every row in the table, I had to change a bit of the `computeRowHeight` function in order to allow to set in the options (of the cells) the height in every row after calculating the height of every line. Maybe it's not the best way to implement it, but at least it worked perfectly for me.

This is what I was hoping to achieve, and I was able to do it. Thank you!
![image](https://user-images.githubusercontent.com/37051987/173887975-982082f6-348e-464d-984b-c10fea0fdabc.png)
```js
[{
  item: '1',
  detail: {
    label: '<b>Website A:</b> <br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin justo turpis, dignissim id mattis id, tristique vel sem. Donec molestie tortor at semper blandit.',
    options: { customHeight: 69.36000000000007 } // <--- Here
  },
  quantity: '1',
  unitPrice: '200000',
  total: '200000'
},
{
  item: '2',
  detail: {
    label: '<b>Website B:</b> <br /><i>No</i> lorem ipsum this time.',
    options: { customHeight: 27.744000000000028 } // <--- Here
  },
  quantity: '2',
  unitPrice: '40000',
  total: '80000'
}]
```

I will make a draft pull request in case you want to review and improve this `customHeight` option.
