### ISSUE TITLE
Headers background

### ISSUE THREAD

**Issue by Tiggum** [natancabral/pdfkit-table#5]
Currently the grey background for the headers only works for the current line, if one of the headers has to linewrap, the next lines will be white instead of gray. 

![headers wrap](https://user-images.githubusercontent.com/3444930/133613728-35bc8793-be90-4241-ae9e-8720f04b8543.PNG)

**Comment by natancabral** [comment]
Hi, Tiggun! 
Done!
`$ npm install pdfkit-table@latest`

**Comment by natancabral** [comment]
Sample:
[file-table-local-large3.pdf](https://github.com/natancabral/pdfkit-table/files/7185763/file-table-local-large3.pdf)
