### ISSUE TITLE
How create a table with border 0 or border:none ?

### ISSUE THREAD

**Issue by morjuax** [natancabral/pdfkit-table#74]

**Comment by LuckyForce** [comment]
With Divider Option

doc.table(table, {
                    divider: {
                        header: { disabled: true },
                        horizontal: { disabled: true, width: 1, opacity: 1 },
                        padding: 5,
                        columnSpacing: 10,
                    },
                    prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {

                    },
                    hideHeader: true
                });
