### ISSUE TITLE
Problem Text 

### ISSUE THREAD

**Issue by DPCLive** [natancabral/pdfkit-table#8]
Hello, I am having a problem in a cell.

My text contains two words, to fit in the width my second word is cut. Can we force the new line without cutting a word?

Sorry, I'm French and this is a translation.

**Comment by natancabral** [comment]
Hi, @DPCLive, 
Did you resolve this?

**Comment by DPCLive** [comment]
Hi @natancabral,
We have enlarged the column and the problem is solved.
On the other hand, is it possible to center the header and not the rest of the column?
Also, is it possible to center vertically in certain columns?

**Comment by natancabral** [comment]
I added a new property, **headerAlign** to simplify for you.
`$ npm install pdfkit-table@latest.`

But the possibility to align vertically cells I will study this case.

**Comment by natancabral** [comment]
I added "valign" on headers options. But is an experimental option. Sample:
https://github.com/natancabral/pdfkit-table#0163
